global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus сам себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Метрики системы
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Метрики Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Метрики вашего backend (если добавите эндпоинт /metrics)
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Метрики PostgreSQL (можно добавить postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']